// <auto-generated />
using System;
using FleetManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201152232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FleetManagement.Models.Izvestaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Izvestaji");
                });

            modelBuilder.Entity("FleetManagement.Models.Servis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoziloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VoziloId");

                    b.ToTable("Servisi");
                });

            modelBuilder.Entity("FleetManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FleetManagement.Models.Vozilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Registracija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VozacId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VozacId");

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("IzvestajVozilo", b =>
                {
                    b.Property<int>("IzvestajId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VozilaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IzvestajId", "VozilaId");

                    b.HasIndex("VozilaId");

                    b.ToTable("IzvestajVozilo");
                });

            modelBuilder.Entity("FleetManagement.Models.Administrator", b =>
                {
                    b.HasBaseType("FleetManagement.Models.User");

                    b.ToTable("Administratori", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Models.Menadzer", b =>
                {
                    b.HasBaseType("FleetManagement.Models.User");

                    b.ToTable("Menadzeri", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Models.Vozac", b =>
                {
                    b.HasBaseType("FleetManagement.Models.User");

                    b.Property<string>("BrojLicence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Vozaci", (string)null);
                });

            modelBuilder.Entity("FleetManagement.Models.Servis", b =>
                {
                    b.HasOne("FleetManagement.Models.Vozilo", "Vozilo")
                        .WithMany("Servisi")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("FleetManagement.Models.Vozilo", b =>
                {
                    b.HasOne("FleetManagement.Models.Vozac", "Vozac")
                        .WithMany("Vozila")
                        .HasForeignKey("VozacId");

                    b.Navigation("Vozac");
                });

            modelBuilder.Entity("IzvestajVozilo", b =>
                {
                    b.HasOne("FleetManagement.Models.Izvestaj", null)
                        .WithMany()
                        .HasForeignKey("IzvestajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManagement.Models.Vozilo", null)
                        .WithMany()
                        .HasForeignKey("VozilaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Models.Administrator", b =>
                {
                    b.HasOne("FleetManagement.Models.User", null)
                        .WithOne()
                        .HasForeignKey("FleetManagement.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Models.Menadzer", b =>
                {
                    b.HasOne("FleetManagement.Models.User", null)
                        .WithOne()
                        .HasForeignKey("FleetManagement.Models.Menadzer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Models.Vozac", b =>
                {
                    b.HasOne("FleetManagement.Models.User", null)
                        .WithOne()
                        .HasForeignKey("FleetManagement.Models.Vozac", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Models.Vozilo", b =>
                {
                    b.Navigation("Servisi");
                });

            modelBuilder.Entity("FleetManagement.Models.Vozac", b =>
                {
                    b.Navigation("Vozila");
                });
#pragma warning restore 612, 618
        }
    }
}
